vote:
  image:
    repository: docker/example-voting-app-vote
    tag: latest
result:
  image:
    repository: docker/example-voting-app-result
    tag: latest
worker:
  image:
    repository: docker/example-voting-app-worker
    tag: latest
  postgresql:
    server: db
  redis:
    host: redis

postgresql:
  fullnameOverride: db
  pgHbaConfiguration: host     all             all             0.0.0.0/0               trust
  postgresqlDatabase: postgres

redis:
  usePassword: false
