apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    chart: svc-fix
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app: redis
    release: redis-{{ .Release.Namespace }}
    role: master
  sessionAffinity: None
